# Generated by Django 3.0.5 on 2020-10-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('content', models.CharField(max_length=120)),
                ('tagline', models.TextField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=12)),
                ('img_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
