# Generated by Django 3.0.5 on 2020-10-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img_file',
        ),
    ]
