# Generated by Django 3.0.5 on 2020-10-25 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_remove_posts_img_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('msg', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=12)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='writer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tagline',
            field=models.CharField(max_length=120),
        ),
    ]
